# Generated by Django 6.0.1 on 2026-01-16 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('frequency', models.CharField(choices=[('Daily', 'Каждый день'), ('Weekly', 'Каждую неделю'), ('Day_about', 'Через день')], default='Daily', max_length=20, verbose_name='Частота выполнения')),
                ('start_date', models.DateField(verbose_name='Начало привычки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_habit', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'db_table_comment': 'Привычки пользователя',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
                ('is_done', models.BooleanField(db_index=True, default=True, verbose_name='Выполнено')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habit_log', to='main.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['habit'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='Нет описания', verbose_name='Описание')),
                ('status', models.CharField(choices=[('todo', 'Не начал'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='Todo', max_length=30, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Приоритет')),
                ('deadline', models.DateField(verbose_name='Дата конца')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table_comment': 'Задачи пользователя',
                'ordering': ['-created_at'],
            },
        ),
    ]
